Add controllers 2
vladrassvet/java-shareit pull request #2
Opened 2023-12-24 13:23 UTC by vladrassvet

2023-12-24 19:11 UTC, Frilock requested changes
Добрый день, в целом все хорошо. ряд мелких комментариев к коду

2023-12-24 19:11 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    private static final String USER_ID = "X-Sharer-User-Id";
static final поля располагают выше остальных

2023-12-24 19:11 UTC, Frilock commented on src/main/java/ru/practicum/shareit/exception/ErrorResponse.java
> +    private final String error;
Можно добавить пару аннотаций от ломбок и упростить данный класс

2023-12-24 19:11 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/storage/ItemStorageImpl.java
> +                .filter(item -> (item.getName().toLowerCase().contains(text.toLowerCase()) ||
Используйте StringUtils.containsIgnoreCase код будет проще

2023-12-24 19:11 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/dto/UserMapper.java
> +@Component
Лишняя аннотация, зачем класс бином делать?

2023-12-24 19:11 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/storage/UserStorageImpl.java
> +        checkUser(user.getId());
user.getId() - делаете больше 2х раз в методе. Сохраните результат в переменную и используйте дальше

2023-12-25 06:41 UTC, vladrassvet commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    private static final String USER_ID = "X-Sharer-User-Id";
Исправлено

2023-12-25 06:44 UTC, vladrassvet commented on src/main/java/ru/practicum/shareit/exception/ErrorResponse.java
> +    private final String error;
Исправлено

2023-12-25 06:47 UTC, vladrassvet commented on src/main/java/ru/practicum/shareit/item/storage/ItemStorageImpl.java
> +                .filter(item -> (item.getName().toLowerCase().contains(text.toLowerCase()) ||
Не найден метод containsIgnoreCase в классе StringUtils. Поэтому исправить не получилось.

2023-12-25 06:48 UTC, vladrassvet commented on src/main/java/ru/practicum/shareit/user/dto/UserMapper.java
> +@Component
Исправлено

2023-12-25 06:51 UTC, vladrassvet commented on src/main/java/ru/practicum/shareit/user/storage/UserStorageImpl.java
> +        checkUser(user.getId());
Исправлено

2023-12-25 19:18 UTC, Frilock approved these changes
Принято, но посмотрите комментарий один

2023-12-25 19:18 UTC, Frilock commented on src/main/java/ru/practicum/shareit/exception/ErrorResponse.java
> +@Slf4j
Вообще имелось ввиду, AllArgsConstructor и Getter, зачем вы сюда логгер добавили я не понял. Ладно не критично

2023-12-26 07:31 UTC, vladrassvet commented on src/main/java/ru/practicum/shareit/exception/ErrorResponse.java
> +@Slf4j
Исправлено

2023-12-26 07:32 UTC, merged