Final Task 14
vladrassvet/java-shareit pull request #3
Opened 2024-01-15 09:38 UTC by vladrassvet

2024-01-15 18:08 UTC, Frilock requested changes
Добрый вечер, пару комментариев к коду

2024-01-15 18:08 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +        return bookings.stream()
можно прям сразу bookingService.getUserBookings(userId, state).stream...

2024-01-15 18:08 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDtoRequest.java
> +
Лишний пропуск строки

2024-01-15 18:08 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/mapper/BookingMapper.java
> +
Лишние пустые строки

2024-01-15 18:08 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            case "ALL":
Данные статусы лучше перенести в енам - дополнительная валидация

2024-01-15 18:08 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/comment/CommentMapper.java
> +
Лишняя пустая строка

2024-01-15 18:08 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (item.getDescription() == null) {
Данную конструкцию можно заменить на Optional.ofNullable(...).ifPresent(...) будет выглядеть компактнее

2024-01-15 18:08 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +            user.setName(oldUser.getName());
Данную конструкцию можно заменить на Optional.ofNullable(...).ifPresent(...) будет выглядеть компактнее

2024-01-15 18:08 UTC, Frilock commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS users(
Зачем добавлять IF NOT EXISTS если вы выше все удалили?

2024-01-15 18:08 UTC, Frilock commented on src/main/resources/schema.sql
> +id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
Предложил бы сделать более приятное форматирование скрипту

2024-01-15 18:08 UTC, Frilock commented on src/main/resources/schema.sql
> +description VARCHAR(2000) NOT NULL,
Данные размерности лучше переносить в аннотацию Column, чтобы лишний раз не лазить в скрипты

2024-01-16 07:11 UTC, vladrassvet commented on src/main/java/ru/practicum/shareit/booking/mapper/BookingMapper.java
> +
Исправлено

2024-01-16 07:12 UTC, vladrassvet commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDtoRequest.java
> +
Исправлено

2024-01-16 07:14 UTC, vladrassvet commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +        return bookings.stream()
Исправлено

2024-01-16 07:14 UTC, vladrassvet commented on src/main/java/ru/practicum/shareit/item/comment/CommentMapper.java
> +
Исправлено

2024-01-16 07:15 UTC, vladrassvet commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS users(
Исправлено

2024-01-16 07:17 UTC, vladrassvet commented on src/main/resources/schema.sql
> +id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
Не совсем понял какое именно форматирование

2024-01-16 07:18 UTC, vladrassvet commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +            user.setName(oldUser.getName());
Возможно, но думаю, что моё решение всё же компактнее и проще. Прошу за ошибку не считать.

2024-01-16 07:19 UTC, vladrassvet commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (item.getDescription() == null) {
Возможно, но думаю, что моё решение всё же компактнее и проще. Прошу за ошибку не считать.

2024-01-16 07:41 UTC, vladrassvet commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            case "ALL":
Не совсем понимаю как сравнивать String со значением из enum. Может пока оставим как есть, это довольно наглядно и компактно в плане кода.

2024-01-16 07:42 UTC, vladrassvet commented on src/main/resources/schema.sql
> +description VARCHAR(2000) NOT NULL,
По логике всё же думаю, что логичнее эти значения прописывать там, где создаются объекты. По крайней мере это только одно место куда потом стоит смотреть.

2024-01-17 06:11 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            case "ALL":
Сравнить значение из енам со строкой - ALL.name().equals("Any string")
Но вообще в этом то и дополнительная защита, что вы вашу строку преобразуете к енаму и сравниваете енам с енамом. valueOf(...) а затем в свитч пихаете

2024-01-17 06:15 UTC, Frilock approved these changes
Принято, но с рядом моментов я не согласен. В целом на работоспособность это не влияет, поэтому принимаю. Комментарии можете посмотреть

2024-01-17 06:15 UTC, Frilock commented on src/main/resources/schema.sql
> +description VARCHAR(2000) NOT NULL,
Нет это не верно. Это сейчас вы написали 1 скрипт для схемы и все здорово и хорошо. Но в реальности вы будете таблицы постоянно менять, добавлять новые поля, увеличивать размерность полей, удалять поля и таблицы и тд и тп. В реальности это делается не руками, а с помощью различных средств миграции, например, liquebase скриптами. И что проще для разработчика зайти в коде в класс модели, чтобы посмотреть на размерность полей, различные флаги (not null и тд) или лезть в БД?

2024-01-17 07:03 UTC, vladrassvet commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            case "ALL":
Спасибо, на будущее буду знать!

2024-01-17 07:05 UTC, vladrassvet commented on src/main/resources/schema.sql
> +description VARCHAR(2000) NOT NULL,
Теперь стало понятнее зачем это делать в коде, на будущее постараюсь так и делать!

2024-01-17 07:05 UTC, merged