Final task 15
vladrassvet/java-shareit pull request #4
Opened 2024-01-29 06:56 UTC by vladrassvet

2024-01-29 18:36 UTC, Frilock requested changes
Добрый вечер, оставил ряд комментариев в коде

2024-01-29 18:36 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +                                                   @Valid @RequestParam(defaultValue = "1") @Min(1) Integer from,
@Valid а для чего она вам тут? По идее должно работать и без нее

2024-01-29 18:36 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +                                                @Valid @RequestParam(defaultValue = "1") @Min(1) Integer from,
Тут везде аналогичный вопрос

2024-01-29 18:36 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
>          return bookings.stream()
Можно обьединить 2 строчки

2024-01-29 18:36 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    List<Booking> findAllByItemOwnerAndStartIsAfterOrderByStartDesc(User user, LocalDateTime now, Pageable pageable);
В методах где работаете с обьектом pageable, можно возвращать обьект page, чтобы явно показать что тут именно обьект страницы
На ваше усмотрение

2024-01-29 18:36 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +                                                                              LocalDateTime now1, LocalDateTime now2,
Даты лучше называть endDate и startDate, а не 1, 2 и тд =)

2024-01-29 18:36 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        User user = userRepository.findById(userId)
Зачем вернули такой поиск? Обьект потом используется который вы поиском нашли?

2024-01-29 18:36 UTC, Frilock commented on src/main/java/ru/practicum/shareit/exception/ErrorResponse.java
> -@Getter
А зачем убираете? Вообще на самом деле такой класс вызывает вопросы, почему просто строку не возвращать? зачем в обьект заворачивать

2024-01-29 18:36 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +                                                             @RequestParam(defaultValue = "20") @Min(1) @Max(20) Integer size) {
Validated над классом не забыли?

2024-01-29 18:36 UTC, Frilock commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +                                                                 @RequestParam(defaultValue = "20") @Min(1) @Max(20) Integer size) {
Validated над классом не забыли?

2024-01-29 18:36 UTC, Frilock commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequest.java
> +    @Column
В данной аннотации принято указывать также размерность поля, которую вы задали в скрипте

2024-01-29 18:36 UTC, Frilock commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestDto.java
> +@Generated
А это зачем?

2024-01-29 18:36 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        // checkUser(user.getId());
Нужно убрать закоментированный код

2024-01-29 18:36 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
>          if (user.getName() == null) {
Данную конструкцию можно заменить на Optional.ofNullable(...).ifPresent(...) будет выглядеть компактнее

2024-01-29 18:36 UTC, Frilock commented on src/main/resources/schema.sql
>  name VARCHAR(255) NOT NULL,
а надо ли столько выделять на имя и имейл?

2024-01-29 18:36 UTC, Frilock commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS users(
Зачем добавлять  IF NOT EXISTS  если вы выше обьекты удаляете?

2024-01-29 18:36 UTC, Frilock commented on src/test/java/ru/practicum/shareit/ShareItAppTest.java
> +    @Test
Бесполезный тест, удалите

2024-01-29 18:36 UTC, Frilock commented on src/test/java/ru/practicum/shareit/ShareItTests.java
>  	void contextLoads() {
Бесполезный тест, удалите

2024-01-29 18:36 UTC, Frilock commented on src/test/java/ru/practicum/shareit/booking/controller/BookingControllerTest.java
> +        item = Item.builder()
Лучше вынести в приватные методы создание таких полей, чтобы "незахламлять" метод инициализации

2024-01-30 07:22 UTC, vladrassvet commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +                                                   @Valid @RequestParam(defaultValue = "1") @Min(1) Integer from,
Исправлено

2024-01-30 07:22 UTC, vladrassvet commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +                                                @Valid @RequestParam(defaultValue = "1") @Min(1) Integer from,
Исправлено

2024-01-30 07:23 UTC, vladrassvet commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
>          return bookings.stream()
Исправлено

2024-01-30 07:24 UTC, vladrassvet commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    List<Booking> findAllByItemOwnerAndStartIsAfterOrderByStartDesc(User user, LocalDateTime now, Pageable pageable);
Принял во внимание. Пока оставил код как есть.

2024-01-30 07:26 UTC, vladrassvet commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +                                                                              LocalDateTime now1, LocalDateTime now2,
Исправлено

2024-01-30 07:28 UTC, vladrassvet commented on src/main/resources/schema.sql
>  name VARCHAR(255) NOT NULL,
Исправил на 128

2024-01-30 07:28 UTC, vladrassvet commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS users(
Удалил DROP ALL OBJECTS в начале

2024-01-30 07:29 UTC, vladrassvet commented on src/test/java/ru/practicum/shareit/ShareItAppTest.java
> +    @Test
Исправлено

2024-01-30 07:30 UTC, vladrassvet commented on src/test/java/ru/practicum/shareit/ShareItTests.java
>  	void contextLoads() {
Исправлено

2024-01-30 07:58 UTC, vladrassvet commented on src/test/java/ru/practicum/shareit/booking/controller/BookingControllerTest.java
> +        item = Item.builder()
Сделал как вы и просили, но по мне создание объектов в одном методе setUp() выглядит логичнее и проще, чем проверка разным отдельных методов.

2024-01-31 07:00 UTC, Frilock requested changes
Доброе утро, часть комментариев которые "схлопнуты" не поправили.

2024-01-31 08:42 UTC, vladrassvet commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        User user = userRepository.findById(userId)
Да, потом объект используется. Как пример, вот метод: bookingList = bookingRepository.findAllByBookingUserOrderByStartDesc(user, pageable);

2024-01-31 08:43 UTC, vladrassvet commented on src/main/java/ru/practicum/shareit/exception/ErrorResponse.java
> -@Getter
Исправлено

2024-01-31 08:44 UTC, vladrassvet commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +                                                             @RequestParam(defaultValue = "20") @Min(1) @Max(20) Integer size) {
Исправлено

2024-01-31 08:45 UTC, vladrassvet commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +                                                                 @RequestParam(defaultValue = "20") @Min(1) @Max(20) Integer size) {
Исправлено

2024-01-31 08:48 UTC, vladrassvet commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequest.java
> +    @Column
Исправлено

2024-01-31 08:49 UTC, vladrassvet commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestDto.java
> +@Generated
Исправлено

2024-01-31 08:50 UTC, vladrassvet commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        // checkUser(user.getId());
Исправлено

2024-01-31 08:52 UTC, vladrassvet commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
>          if (user.getName() == null) {
Можно заменить, но по мне так user.getName() == null выглядит проще и понятнее. Прошу за ошибку не считать, код работает и выглядит довольно компактно с данным выражением.

2024-01-31 09:18 UTC, vladrassvet commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestDto.java
> +@Generated
Без этих аннотаций тесты pull request не проходят. Оставил как есть.

2024-01-31 13:38 UTC, Frilock approved these changes
Принято

2024-01-31 14:16 UTC, merged