Final task 16
vladrassvet/java-shareit pull request #5
Opened 2024-02-10 08:17 UTC by vladrassvet

2024-02-10 17:43 UTC, Frilock requested changes
Валидации в подмодуле server быть не должно

2024-02-10 17:43 UTC, Frilock commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingClient.java
> +            parameters = Map.of(
В 1 строку влезает, зачем переносить

2024-02-10 17:43 UTC, Frilock commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingClient.java
> +            parameters = Map.of(
В 1 строку влезает, зачем переносить

2024-02-10 17:43 UTC, Frilock commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingClient.java
> +            parameters = Map.of(
В 1 строку влезает, зачем переносить

2024-02-10 17:43 UTC, Frilock commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingClient.java
> +
Не оставляйте пропуски до и после

2024-02-10 17:43 UTC, Frilock commented on server/src/main/java/ru/practicum/shareit/booking/dto/BookingDtoRequest.java
> +    @NotNull
Валидации входных данных в подмодуле сервера быть не должно, ее нужно перенести в gateway

2024-02-10 17:43 UTC, Frilock commented on server/src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            case "ALL":
я бы значения перенес в енам, так было бы правильнее - дополнительная валидация

2024-02-11 10:49 UTC, vladrassvet commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingClient.java
> +            parameters = Map.of(
Исправлено

2024-02-11 10:49 UTC, vladrassvet commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingClient.java
> +            parameters = Map.of(
Исправлено

2024-02-11 10:50 UTC, vladrassvet commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingClient.java
> +
Исправлено

2024-02-11 10:50 UTC, vladrassvet commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingClient.java
> +            parameters = Map.of(
Исправлено

2024-02-11 10:51 UTC, vladrassvet commented on server/src/main/java/ru/practicum/shareit/booking/dto/BookingDtoRequest.java
> +    @NotNull
Исправлено

2024-02-11 10:53 UTC, vladrassvet commented on server/src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            case "ALL":
Почему-то IDEA не видит созданный enum, поэтому решил оставить как есть. Просьба за ошибку не считать.

2024-02-11 18:19 UTC, Frilock requested changes
Добрый вечер, валидацию нужно убрать из всех классов dto подмодуля server. Те тесты которые перестанут проходить, нужно перенести в подмодуль gateway, как и логику валидации. Кроме того, при отправке работы, смотрите, что у вас проходят тесты на гитхаб, иначе такую работу я принять не смогу

2024-02-11 18:19 UTC, Frilock commented on server/src/test/java/ru/practicum/shareit/booking/controller/BookingControllerTest.java
>      @Test
Тесты с валидацией, которые перестанут проходить нужно перенести в gateway

2024-02-12 07:16 UTC, vladrassvet commented on server/src/test/java/ru/practicum/shareit/booking/controller/BookingControllerTest.java
>      @Test
Исправлено

2024-02-12 17:27 UTC, Frilock approved these changes
Принято

2024-02-12 17:33 UTC, merged